name: Build & Publish YidCal Release

on:
  push:
    # Triggers on tags like v0.1.7
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Extract the version from the tag
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 3) Zip the integration
      - name: Package YidCal
        run: |
          zip -r yidcal.zip . \
            -x .git/\* \
            -x .github/\*
          echo "ASSET=yidcal.zip" >> $GITHUB_ENV

      # 4) Create or update the GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: YidCal ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5) Upload the ZIP as a Release asset
      - name: Upload ZIP Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
